### ISSUE TITLE
Without the {subject_name}_minimal_tpose.ply

### ISSUE THREAD

**Issue by RxChi1d** [YuxuanSnow/NeuralSurfaceField#1]
Hi,
When I try to obtain prediffused SMPL skinning weights field following the FITE, and I don't know what the {subject_name}_minimal_tpose.ply and the scans (which must be closed meshes) as .npz files should I use. I can't find it anywhere.
Can you tell me how to do?

Thanks!

**Comment by YuxuanSnow** [comment]
Hi,
i guess you have question regarding the data preparation (2nd step) in FiTE.

The minimal tpose means the SMPL registration of the subject with the minimal clothing in T-pose (The canonical pose we desire). It can be downloaded from the CAPE website (https://cape.is.tue.mpg.de/). 

If you have any further question, please let me know.
